---
- hosts: nodo1
  become: yes
  tasks: 
        - name: instalar mariadb
          apt:
                  name: mariadb-server
                  update_cache: yes

        - name: crear base de datos
          mysql_db:
                  name: wordpress
                  state: present

        - name: crear usuario
          mysql_user:
                  name: usuario
                  password: usuario
                  priv: '*.*:ALL'
                  host_all: yes
                  state:  present
