---
- hosts: nodo1
  become: yes
  tasks:
          - name: instalar bind9
            apt:
                    name: bind9
                    update_cache: yes

          - name: copiar fichero del dominio
            template:
                    src: bind9/named.conf.local
                    dest: /etc/bind/named.conf.local
