---
- hosts: nodo1
  become: yes
  tasks:
          - name: instalar bind9
            apt:
                    name: bind9
                    update_cache: yes

          - name: copiar fichero del dominio
            template:
                    src: bind9/named.conf.local
                    dest: /etc/bind/named.conf.local

          - name: copiar zona directa del dominio
            template:
                    src: bind9/db.nodos.com
                    dest: /var/cache/bind/db.nodos.com

          - name: copiar zona inversa del dominio
            template:
                    src: bind9/db.100.168.192
                    dest: /var/cache/bind/db.100.168.192

          - name: reiniciar servicio
            service:
                    name: bind9
                    state: restarted
