---
- hosts: nodo1
  become: yes
  tasks: 
        - name: instalar mysql
          apt:
                  name: mysql-server
                  update_cache: yes

	- name: crear base de datos
	  mysql_db: db=wordpress state=present

	- name: crear usuario
	  mysql_user: user=usuario password=usuario priv=*.*:ALL state=present
