---
- hosts: nodo1
  become: yes
  tasks: 
        - name: instalar mysql
          apt: name={{ item }} state=present
          with_items:
                  - mysql-server
                  - python-mysqldb

        - name: crear base de datos
          mysql_db:
                  name: wordpress
                  state: present

        - name: crear usuario
          mysql_user:
                  name: usuario
                  password: usuario
                  priv: '*.*:ALL'
                  host_all: yes
                  state:  present

        - name: configuracion del fichero de mysql
          template:
                  src: mysql/50-server.cnf
                  dest: /etc/mysql/mariadb.conf/50-server.cnf
                  owner: root
                  group: root
                  mode: 0644

        - name: copiar fichero sql
          template:
                  src: mysql/wordpress.sql
                  dest: /tmp

        - name: importar base de datos
          mysql_db:
                  name: wordpress
                  state: import
                  dest: /tmp/wordpress.sql


        - name: reiniciar servicio mysql
          service:
                  name: mysql
                  state: restarted
