---
- hosts: nodo1
  become: yes
  tasks: 
        - name: instalar mysql
          apt:
                  name: mysql-server
                  update_cache: yes

	- name: Start MySQL service
	service:
		name: "mysql"
		state: started
		enabled: yes

	- name: Setup MySQL root password
	mysql_user:
		name: "root"
		password: "mysql"
		host: "{{ item }}"
		state: present
		with_items:
		- "{{ ansible_hostname }}"
		- 127.0.0.1
		- ::1
		- localhost

	- name: Setup MySQL creds for root user
	template:
		src: "{{ mysqlTemplatePath }}"
		dest: "/root/.my.cnf"
		owner: "root"
		mode: 0600

	- name: Setup empty database for WordPress
	mysql_db:
		name: "wordpress"
		encoding: "utf8"
		collation: "utf8_unicode_ci"
		state: "present"
		login_user: "root"
		login_password: "mysql"

	- name: Setup MySQL user for WordPress
	mysql_user:
		name: "user_wp"
		password: "wordpress"
		host: "localhost"
		priv: "wordpress.*:ALL"
		state: "present"

