---
- hosts: nodo2
  become: yes
  tasks:
          - name: instalar zip
            apt:
                    name: unzip
                    update_cache: yes

          - name: Extraer wordpress
            unarchive:
                    src: wordpress/wordpress-4.9.2-es_ES.zip
                    dest: /var/www/html
                    owner: www-data
                    group: www-data

          - name: copiar fichero wordpress
            copy:
                    src: wordpress/wp-config.php 
                    dest: /var/www/html/wordpress/wp-config.php
                    owner: www-data
                    group: www-data

          - name: reiniciar nginx
            service: name=nginx state=restarted
            become: yes

          - name: reiniciar fpm
            service: name=php7.0-fpm state=restarted
            become: yes
