---
- hosts: nodo2
  become: yes
  tasks:
          - name: instalar nginx
            apt:
                    name: nginx
                    update_cache: yes

          - name: configuracion de virtualhost
            template:
                    src: nginx/default
                    dest: /etc/nginx/sites-available/default
         
          - name: reiniciar servicio
            service:
                    name: nginx
                    state: restarted
