---
- hosts: nodo2
  become: yes
  tasks:
          - name: instalar FPM y complemento
            apt: name={{ item }} state=latest update_cache=yes
            with_items:
                    - php7.0
                    - php7.0-fpm
                    - php7.0-mysql

            - name: reiniciar php
              service:
                      name: php7.0-fpm
                      state: restarted
