---
- hosts: nodo2
  become: yes
  tasks:
          - name: instalar nginx
            apt:
                    name: nginx
                    update_cache: yes

          - name: instalar zip
            apt:
                    name: unzip
                    update_cache: yes
          
          - name: configuracion de virtualhost
            template:
                    src: nginx/default
                    dest: /etc/nginx/sites-available/default

          - name: copiar wordpress
            template:
                    src: wordpress/wordpress-4.9.2-es_ES.zip
                    dest: /tmp

          - name: descomprimir fichero y moverlo a html
            unarchive:
                    src: /tmp/wordpress-4.9.2-es_ES.zip
                    dest: /var/www/html
                    owner: www-data
                    group: www-data

          - name: copiar fichero wordpress
            template:
                    src: wordpress/wp-config.php
                    dest: /var/www/html
         
          - name: reiniciar servicio
            service:
                    name: nginx
                    state: restarted
