---
- hosts: nodo2
  become: yes
  tasks:
          - name: instalar nginx
            apt:
                    name: nginx
                    update_cache: yes

          - name: instalar zip
            apt:
                    name: zip
                    update_cache: yes

          - name: eliminar default generado
            command: rm /etc/nginx/sites-availables/default
          
          - name: configuracion de virtualhost
            template:
                    src: nginx/default
                    dest: /etc/nginx/sites-availables/default


          
          - name: reiniciar servicio
            servicio: name=nginx state=restarted
