; BIND reverse data file for empty rfc1918 zone
;
; DO NOT EDIT THIS FILE - it is used for multiple zones.
; Instead, copy it, edit named.conf, and use that copy.
;
$TTL 86400
@	IN	SOA	nodo1.nodos.com. admin.email. (
	5	;	Serial
	604800	;	Refresh
	86400	;	Retry
	2419200	;	Expire
	86400 )	;	Negative Cache TTL
;
@	IN	NS	nodo1.nodos.com.

$ORIGIN	nodos.com.
nodo1	IN	A	192.168.100.251
nodo2	IN	A	192.168.100.252
www	IN	CNAME	nodo2
